### ISSUE TITLE
n_jobs parrallel processing

### ISSUE THREAD

**Issue by mcguires5** [secML/secML.github.io#25]
On line 155 of the c_classifier file self._fit(CDataset(data_x, dataset.Y), n_jobs=n_jobs) continues to error, removing the second parameter resolves this, I believe this should be removed as it appears parallel processing is not implemented correctly

**Comment by evansuva** [comment]
Is this the right repository? This is the repository for the website for the seminar, so I'm not sure which code you are referring to here.
