### ISSUE TITLE
Hessian for influence function

### ISSUE THREAD

**Issue by Cinofix** [secML/secML.github.io#27]
The function explain function in secml.explanation.c_explainer_influence_functions.CExplainerInfluenceFunctions should compute the Hessian matrix of the model's parameters with respect to the training points, see Koh, P. W., & Liang, P. (2017, July). Understanding black-box predictions via influence functions. 

Indeed, the current implementation gets the Hessian with respect to the sample given at test time. 

[Line 88](https://gitlab.com/secml/secml/-/blob/v0.13-stable/src/secml/explanation/c_explainer_influence_functions.py#L88) should be: 

`H = self.hessian(self.tr_ds.X, self.tr_ds.Y)`

**Comment by evansuva** [comment]
I'm not sure what this is referring to here - I think you may have meant to submit this to a different repository (https://gitlab.com/secml/ ?) - this is one for a seminar that was run in 2018 - https://secml.github.io/. If you did find something to correct there, I appreciate the notice and would want to correct it.

**Comment by Cinofix** [comment]
Ok sorry, I would say that I was completely wrong :D You may remove the issue!
